version: '2'
services:
  node:
    build: .
    ports:
      - "3000:3000"
      command: node index.js
    environment: 
      MONGO_URL: "mongodb://mongo:27017"
  mongo:
    image: mongo:3.4.6
    ports:
      - "27017:27017"
